#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND %BUILDREQ );

%PREREQ = (
    'Lingua::EN::Numbers' => 0,
    'I18N::LangTags'      => '0.35',
);

%RECOMMEND = (
    'Task::Lingua::Any::Numbers' => '0.12',
);

%BUILDREQ = (
    'Test::More' => '0.40',
);

if ( $^O =~ m{MSWin}i ) {
    $PREREQ{'Win32::Locale'} = 0;
}

1;
