#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND);

%PREREQ = (
    'Lingua::EN::Numbers' => 0,
    'Test::More'          => '0.40',
    'I18N::LangTags'      => '0.35',
);

%RECOMMEND = (
    'Lingua::AF::Numbers' => 0,
    'Lingua::EU::Numbers' => 0,
    'Lingua::FR::Numbers' => 0,
    'Lingua::HU::Numbers' => 0,
    'Lingua::IT::Numbers' => 0,
    'Lingua::JA::Numbers' => 0,
    'Lingua::NL::Numbers' => 0,
    'Lingua::PL::Numbers' => 0,
    'Lingua::TR::Numbers' => 0,
    'Lingua::ZH::Numbers' => 0,
);

if ( $^O =~ m{MSWin}i ) {
   $PREREQ{'Win32::Locale'} = 0;
}

1;

__END__
